#! /bin/sh

#
# CONFIGURATION SECTION
#
if [ -z "$PIC30_CD" ]; then
    echo "Environmental variable PIC30_CD must be set up.";
    exit 1;
fi

GCC="$PIC30_CD/bin/xc16-gcc -save-temps -mno-info-linker -mcpu=33AK128MC106 -Tp33AK128MC106.gld -Wl,--no-data-init"
OBJDUMP="$PIC30_CD/bin/xc16-objdump"

#
# END CONFIGURATION
#

# process args
vflag=off
while [ $# -gt 0 ]
do
    case "$1" in
        -v)  vflag=on;;
    esac
    shift
done

rm -f t1.o t.exe

$GCC -o t.exe t1.s || exit 99
err=$?
if [ $vflag = "on" ]; then
    echo "$GCC -o t.exe t1.s"
    echo $err
fi

rm -f test.out
#$OBJDUMP -dr t1.o > test.obj
$OBJDUMP -d -j .text t.exe > test.out

echo
echo `head -1 info.txt`

if [ $vflag = "on" ]; then
    diff -b -B test.out expect.out
else
    diff -b -B test.out expect.out > /dev/null
fi


if [ $? -ne 0 ]; then
    echo "ERRORs Detected!!"
    echo
    exit 199
fi

echo "All Tests Pass"
echo
exit 0
