#! /bin/sh

#
# CONFIGURATION SECTION
#
if [ -z "$PIC30_CD" ]; then
    echo "Environmental variable PIC30_CD must be set up.";
    exit 1;
fi

if [ -z "$MDB" ]; then
    echo "Environmental variable MDB must be set up.";
    exit 1;
fi

GCC30="$PIC30_CD/bin/xc16-gcc -omf=elf"

#
# END CONFIGURATION
#

# process args
vflag=off
while [ $# -gt 0 ]
do
    case "$1" in
        -v)  vflag=on;;
    esac
    shift
done


rm -f t.exe
$GCC30 -mcpu=30F6014 -o t.exe t1.c -mconst-in-data -Wl,--heap=512 || exit 99
err=$?
if [ $vflag = "on" ]; then
    echo "$GCC30 -o t.exe t1.c -mconst-in-data -Wl,--heap=512"
    echo $err
fi

rm -f uartout.txt test.out sim.out
if [ $vflag = "on" ]; then
    echo
    echo "$MDB run.cmd >sim.out 2>&1"
    echo
fi
$MDB run.cmd >sim.out 2>&1
cp uartout.txt test.out
rm -f uartout.txt

echo
echo `head -1 info.txt`

if [ $vflag = "on" ]; then
    diff -b -B test.out expect.out
else
    diff -b -B test.out expect.out > /dev/null
fi


if [ $? -ne 0 ]; then
    echo "ERRORs Detected!!"
    echo
    exit 199
fi

echo "All Tests Pass"
echo
exit 0
