#! /bin/sh

#
# CONFIGURATION SECTION
#
if [ -z "$PIC30_CD" ]; then
    echo "Environmental variable PIC30_CD must be set up.";
    exit 1;
fi

GAS30="$PIC30_CD/bin/xc16-as -omf=elf -W"
GLD30="$PIC30_CD/bin/xc16-ld -omf=elf"
OBJDUMP="$PIC30_CD/bin/xc16-objdump -omf=elf"

#
# END CONFIGURATION
#

# process args
vflag=off
while [ $# -gt 0 ]
do
    case "$1" in
        -v)  vflag=on;;
    esac
    shift
done

rm -f t1.o
OPTS=" -o t1.o t1.s"
if [ $vflag = "on" ]; then
    echo
    echo "$GAS30 $OPTS"
fi
$GAS30 $OPTS
err=$?
if [ $vflag = "on" ]; then
    echo $err
fi


rm -f t.exe
OPTS="--script=t.lkr -o t.exe t1.o --boot=flash_size=256"
if [ $vflag = "on" ]; then
    echo "$GLD30 $OPTS"
fi
$GLD30 $OPTS
err=$?
if [ $vflag = "on" ]; then
    echo $err
fi

if [ $vflag = "on" ]; then
    $OBJDUMP -d -j .text t.exe || exit 99
    echo
fi

rm -f test.out
$OBJDUMP -s -j .text t.exe > test.out

echo
echo `head -1 info.txt`

if [ $vflag = "on" ]; then
    diff -b -B test.out expect.out
else
    diff -b -B test.out expect.out > /dev/null
fi


if [ $? -ne 0 ]; then
    echo "ERRORs Detected!!"
    echo
    exit 199
fi

echo "All Tests Pass"
echo
exit 0
